### ISSUE TITLE
date() expects parameter 2 to be integer, float given

### ISSUE THREAD

**Issue by adojck** [kmielke/calendar-extended-bundle#20]
Hello,

I get a Warning when using this extension:
`date() expects parameter 2 to be integer, float given`

This warning occurs `in vendor/kmielke/calendar-extended-bundle/src/Resources/contao/classes/EventsExt.php (line 175)`

I catch this on FE when using Debug Mode.

Contao Version 4.8.4

**Comment by tarun-uwe** [comment]
Our module was configured with "next_all" and the **Contao** function [getDatesFromFormat](https://github.com/contao/contao/blob/4.8/calendar-bundle/src/Resources/contao/classes/Events.php#L498-L549) returns an float instead an integer.

Probably because of https://github.com/contao/contao/issues/811 and furthermore https://github.com/contao/contao/pull/814

We solved our problem by changing it to the next two-year option.

![image](https://user-images.githubusercontent.com/30664429/67763217-74295a80-fa47-11e9-9f27-0b72e1d9e206.png)

**Comment by tarun-uwe** [comment]
It has to be fixed in Contao I think, because Typecasting returns -1. 

![image](https://user-images.githubusercontent.com/30664429/67763608-67f1cd00-fa48-11e9-9eac-65f1c538da42.png)

**Comment by kmielke** [comment]
Contao Bug
